# Generated by Django 5.0.1 on 2024-01-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('names', models.CharField(max_length=255, verbose_name='Author names')),
                ('surnames', models.CharField(max_length=255, verbose_name='Author surnames')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('web', models.URLField(blank=True, null=True, verbose_name='Web')),
                ('mail', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Mail')),
                ('state', models.BooleanField(default=True, verbose_name='Author active/no active')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Creation date')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Category name')),
                ('state', models.BooleanField(default=True, verbose_name='Category enable/disabled')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Creation date')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
