# Generated by Django 5.0.1 on 2024-01-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='mail',
            field=models.EmailField(max_length=254, verbose_name='E-Mail'),
        ),
    ]
